//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHChem.OPCMonitor.SMSServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TKSend", ReplyAction="*")]
        WHChem.OPCMonitor.SMSServiceReference.TKSendResponse TKSend(WHChem.OPCMonitor.SMSServiceReference.TKSendRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSOfInterface", ReplyAction="*")]
        WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceResponse SendSMSOfInterface(WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TKReceiveSMS", ReplyAction="*")]
        WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSResponse TKReceiveSMS(WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 tel 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        WHChem.OPCMonitor.SMSServiceReference.SendMessageResponse SendMessage(WHChem.OPCMonitor.SMSServiceReference.SendMessageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/receiveMessage", ReplyAction="*")]
        WHChem.OPCMonitor.SMSServiceReference.receiveMessageResponse receiveMessage(WHChem.OPCMonitor.SMSServiceReference.receiveMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TKSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TKSend", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.TKSendRequestBody Body;
        
        public TKSendRequest() {
        }
        
        public TKSendRequest(WHChem.OPCMonitor.SMSServiceReference.TKSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TKSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TelList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content;
        
        public TKSendRequestBody() {
        }
        
        public TKSendRequestBody(string UserName, string PassWord, string TelList, string Content) {
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.TelList = TelList;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TKSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TKSendResponse", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.TKSendResponseBody Body;
        
        public TKSendResponse() {
        }
        
        public TKSendResponse(WHChem.OPCMonitor.SMSServiceReference.TKSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TKSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TKSendResult;
        
        public TKSendResponseBody() {
        }
        
        public TKSendResponseBody(int TKSendResult) {
            this.TKSendResult = TKSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSOfInterfaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSOfInterface", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceRequestBody Body;
        
        public SendSMSOfInterfaceRequest() {
        }
        
        public SendSMSOfInterfaceRequest(WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSOfInterfaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TelList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content;
        
        public SendSMSOfInterfaceRequestBody() {
        }
        
        public SendSMSOfInterfaceRequestBody(string UserName, string PassWord, string TelList, string Content) {
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.TelList = TelList;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSOfInterfaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSOfInterfaceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceResponseBody Body;
        
        public SendSMSOfInterfaceResponse() {
        }
        
        public SendSMSOfInterfaceResponse(WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSOfInterfaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSMSOfInterfaceResult;
        
        public SendSMSOfInterfaceResponseBody() {
        }
        
        public SendSMSOfInterfaceResponseBody(int SendSMSOfInterfaceResult) {
            this.SendSMSOfInterfaceResult = SendSMSOfInterfaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TKReceiveSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TKReceiveSMS", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSRequestBody Body;
        
        public TKReceiveSMSRequest() {
        }
        
        public TKReceiveSMSRequest(WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TKReceiveSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PassWord;
        
        public TKReceiveSMSRequestBody() {
        }
        
        public TKReceiveSMSRequestBody(string UserName, string PassWord) {
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TKReceiveSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TKReceiveSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSResponseBody Body;
        
        public TKReceiveSMSResponse() {
        }
        
        public TKReceiveSMSResponse(WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TKReceiveSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TKReceiveSMSResult;
        
        public TKReceiveSMSResponseBody() {
        }
        
        public TKReceiveSMSResponseBody(string TKReceiveSMSResult) {
            this.TKReceiveSMSResult = TKReceiveSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(WHChem.OPCMonitor.SMSServiceReference.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string tel, string name, string Content) {
            this.tel = tel;
            this.name = name;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(WHChem.OPCMonitor.SMSServiceReference.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(int SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveMessage", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.receiveMessageRequestBody Body;
        
        public receiveMessageRequest() {
        }
        
        public receiveMessageRequest(WHChem.OPCMonitor.SMSServiceReference.receiveMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class receiveMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tel;
        
        public receiveMessageRequestBody() {
        }
        
        public receiveMessageRequestBody(string name, string tel) {
            this.name = name;
            this.tel = tel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WHChem.OPCMonitor.SMSServiceReference.receiveMessageResponseBody Body;
        
        public receiveMessageResponse() {
        }
        
        public receiveMessageResponse(WHChem.OPCMonitor.SMSServiceReference.receiveMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class receiveMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int receiveMessageResult;
        
        public receiveMessageResponseBody() {
        }
        
        public receiveMessageResponseBody(int receiveMessageResult) {
            this.receiveMessageResult = receiveMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WHChem.OPCMonitor.SMSServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WHChem.OPCMonitor.SMSServiceReference.ServiceSoap>, WHChem.OPCMonitor.SMSServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WHChem.OPCMonitor.SMSServiceReference.TKSendResponse WHChem.OPCMonitor.SMSServiceReference.ServiceSoap.TKSend(WHChem.OPCMonitor.SMSServiceReference.TKSendRequest request) {
            return base.Channel.TKSend(request);
        }
        
        public int TKSend(string UserName, string PassWord, string TelList, string Content) {
            WHChem.OPCMonitor.SMSServiceReference.TKSendRequest inValue = new WHChem.OPCMonitor.SMSServiceReference.TKSendRequest();
            inValue.Body = new WHChem.OPCMonitor.SMSServiceReference.TKSendRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.TelList = TelList;
            inValue.Body.Content = Content;
            WHChem.OPCMonitor.SMSServiceReference.TKSendResponse retVal = ((WHChem.OPCMonitor.SMSServiceReference.ServiceSoap)(this)).TKSend(inValue);
            return retVal.Body.TKSendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceResponse WHChem.OPCMonitor.SMSServiceReference.ServiceSoap.SendSMSOfInterface(WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceRequest request) {
            return base.Channel.SendSMSOfInterface(request);
        }
        
        public int SendSMSOfInterface(string UserName, string PassWord, string TelList, string Content) {
            WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceRequest inValue = new WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceRequest();
            inValue.Body = new WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.TelList = TelList;
            inValue.Body.Content = Content;
            WHChem.OPCMonitor.SMSServiceReference.SendSMSOfInterfaceResponse retVal = ((WHChem.OPCMonitor.SMSServiceReference.ServiceSoap)(this)).SendSMSOfInterface(inValue);
            return retVal.Body.SendSMSOfInterfaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSResponse WHChem.OPCMonitor.SMSServiceReference.ServiceSoap.TKReceiveSMS(WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSRequest request) {
            return base.Channel.TKReceiveSMS(request);
        }
        
        public string TKReceiveSMS(string UserName, string PassWord) {
            WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSRequest inValue = new WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSRequest();
            inValue.Body = new WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            WHChem.OPCMonitor.SMSServiceReference.TKReceiveSMSResponse retVal = ((WHChem.OPCMonitor.SMSServiceReference.ServiceSoap)(this)).TKReceiveSMS(inValue);
            return retVal.Body.TKReceiveSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WHChem.OPCMonitor.SMSServiceReference.SendMessageResponse WHChem.OPCMonitor.SMSServiceReference.ServiceSoap.SendMessage(WHChem.OPCMonitor.SMSServiceReference.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public int SendMessage(string tel, string name, string Content) {
            WHChem.OPCMonitor.SMSServiceReference.SendMessageRequest inValue = new WHChem.OPCMonitor.SMSServiceReference.SendMessageRequest();
            inValue.Body = new WHChem.OPCMonitor.SMSServiceReference.SendMessageRequestBody();
            inValue.Body.tel = tel;
            inValue.Body.name = name;
            inValue.Body.Content = Content;
            WHChem.OPCMonitor.SMSServiceReference.SendMessageResponse retVal = ((WHChem.OPCMonitor.SMSServiceReference.ServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WHChem.OPCMonitor.SMSServiceReference.receiveMessageResponse WHChem.OPCMonitor.SMSServiceReference.ServiceSoap.receiveMessage(WHChem.OPCMonitor.SMSServiceReference.receiveMessageRequest request) {
            return base.Channel.receiveMessage(request);
        }
        
        public int receiveMessage(string name, string tel) {
            WHChem.OPCMonitor.SMSServiceReference.receiveMessageRequest inValue = new WHChem.OPCMonitor.SMSServiceReference.receiveMessageRequest();
            inValue.Body = new WHChem.OPCMonitor.SMSServiceReference.receiveMessageRequestBody();
            inValue.Body.name = name;
            inValue.Body.tel = tel;
            WHChem.OPCMonitor.SMSServiceReference.receiveMessageResponse retVal = ((WHChem.OPCMonitor.SMSServiceReference.ServiceSoap)(this)).receiveMessage(inValue);
            return retVal.Body.receiveMessageResult;
        }
    }
}
